### ISSUE TITLE
BBOX query specification

### ISSUE THREAD

**Issue by emiliom** [ioos/ioos-sos-issues-generic#2]
Thanks for starting this repo, @abirger.

I'm "opening" this issue only as a reference to [the relevant, generic discussions we had in January about the BBOX query specification, at the i52n-sos repo](https://github.com/ioos/i52n-sos/issues/25).

Feel free to close it w/o any additional comments. I thought it'd be useful to have this reference, even as a closed issue.

**Comment by srstsavage** [comment]
@emiliom This one also seems unnecessary, since it only affects i52n-sos. I don't think we want to duplicate every issue on this repo, just large scale issues affecting both implementations or the spec that need larger discourse.

**Comment by emiliom** [comment]
Yeah, the issue only affected i52n-sos, bu the issue discussions were very much wide ranging and led to updates/clarifications to the IOOS SOS documentation.

Anyway, I'm fine either way (ditto for #3). I totally agree that we don't want to duplicate every issue. But there will also be cases where an issue that seemed specific to one implementation ends up involving useful, generic discussions and uncovering generic ambiguities.

**Comment by abirger** [comment]
@emiliom , I think that you were right to open this issue here as reference but since it has been resolved already, we should close it here as well.
